bunkerity/bunkerweb

- README.md
- confs/nginx.conf
- confs/proxy-real-ip.conf
- entrypoint.sh
Added the ability to see Real IPs if Nginx is running under another proxy (such as Traefik).
> Added the ability to see Real IPs running under another proxy

- README.md
I've noticed that there is a broken line in there and also a missing space.
> Fix broken line in README

- confs/site/reverse-proxy-headers.conf
X-Forwarded-Host (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host)[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host]
> Add last missing reverse proxy header

- entrypoint/site-config.sh
> Fix truncated 3

- README.md
- confs/site/server.conf
- entrypoint/site-config.sh
> Add before `server {}` config.

- compile.sh
Upgrade crowdsecurity/lua-cs-bouncer to latest version to include commit https://github.com/crowdsecurity/lua-cs-bouncer/commit/dcfba46ccd769179d84a5d24aef1930b70382129
> Upgrade crowdsecurity/lua-cs-bouncer

- entrypoint/site-config.sh
- entrypoint/utils.sh
> Fix env variable with space are truncated

- confs/site/main-lua.conf
> Fix lua mistake

- scripts/exit-nodes.sh
generate the file in a much more improved way (2 commands)
> improve generation of block file (Tor exit nodes)

- scripts/referrers.sh
Use one sed command instead of a loop for each line
> more optimized way to generate map referrer file

- confs/site/reverse-proxy.conf
This help improves performance.
> Allow keep alive connection when ws is off

- core/modsecurity/confs/server-http/modsecurity-rules.conf.modsec
- core/modsecurity/plugin.json
- docs/settings.md
Usefull for customizing sites (on/DetectionOnly, Custom logs)
> Add MODSECURITY_SEC_RULE_ENGINE and MODSECURITY_SEC_AUDIT_LOG_PARTS

- src/ui/static/css/dashboard.css
- src/ui/static/js/services.js
- src/ui/static/js/utils/file.manager.js
- src/ui/templates/file-manager.html
- src/ui/templates/flashs.html
- src/ui/templates/footer.html
- src/ui/templates/header.html
- src/ui/templates/logs.html
- src/ui/templates/menu.html
- src/ui/templates/news.html
- src/ui/templates/plugins.html
- src/ui/templates/services-modal.html
- src/ui/templates/services.html
- src/ui/templates/settings_plugins.html
- src/ui/templates/settings_tabs.html
- global darkmode and style enhance
- some title, button and text are now lighter for visibility
- add toggle multiple
- fix show/hide toggle gap between created multiples and existed ones
- fix jinja error logic to display right svg depending type of element (folder, file, root...)
- fix editor not following dark mode on page load
- change job svg to differenciate it with valid info
- replace actions btns on file manager
- factorisation of services multiple class
- avoid value "null" by adding services-name on new service button and set this value on modal name and OLD_SERVER_NAME input (ignore with new operation)
> enhance style/darkmode + add multiple toggle + fix/factorisation script

- src/ui/templates/settings_tabs.html
*add condition to add name service setting only on services templates
> add condition for services

- src/ui/static/js/utils/file.manager.js
*fix the way to select and display dropdown actions for file manager to avoid error with folders that have same names attributs
> fix file manager dropdown

- src/ui/static/css/dashboard.css
- src/ui/static/js/global_config.js
- src/ui/static/js/services.js
- src/ui/static/js/utils/form.js
- src/ui/templates/settings_general.html
- src/ui/templates/settings_plugins.html
*password inps have a toggle visible/invisible value 
*add this logic to all related pages
> handle password inp

- src/ui/static/css/dashboard.css
- src/ui/static/js/plugins.js
- src/ui/templates/file-manager.html
- src/ui/templates/flashs.html
- src/ui/templates/jobs.html
- src/ui/templates/logs.html
- src/ui/templates/plugins.html
*enhance dropdown style
*disabled reload btn if no valid plugin uploaded
*change some title styles
*change file manager icons stroke
*enhance files download for jobs
*fix messages number not display
> enhance style + some fix

- src/ui/static/js/global.js
- src/ui/static/js/services.js
- src/ui/templates/settings_plugins.html
*add _SCHEMA ton input multiple to avoid conflict with regular input
*first multiple has now no suffix, second one start with suffix 1 like server-side
*change service multiple rendering logic by better sorting of settings, removing filtering and nested logic on rendering
*add comments to better understand new logic
*create common pattern for add and rendering multiple to reduce code
*flash count dynamic on remove
> fix and enhance multiple (+ flash)

- src/ui/static/css/dashboard.css
- src/ui/static/js/cache.js
- src/ui/static/js/global.js
- src/ui/static/js/logs.js
- src/ui/static/js/services.js
- src/ui/tailwind.config.js
- src/ui/templates/home.html
- src/ui/templates/loading.html
- src/ui/templates/logs.html
- src/ui/templates/plugins.html
- src/ui/templates/services-modal.html
- src/ui/templates/settings_plugins.html
*fix error that made default-method used to determine disabled/enabled service setting state instead of right method 
*create new method attribut with the current service setting method state, default-method is now use for new-service or/and legacy
*fix filter that sometimes didn't open modal when clicking on edit button 
*new service btn is now setting default-value and setting all settings methods to default (all enabled) 
*fix syntax error with input variable that didn't set the service checkbox right values and method 
*change handlers by type action on regular settings and multiple settings, with common functions to be cleaner 
*sort logic between class, some multiple logic that used to be in regular class logic is now in multiple class 
*fix some other minor logic error and …
> change and fix service logic

- src/common/core/letsencrypt/plugin.json
> Added sub-address support for `EMAIL_LETS_ENCRYPT`

- examples/community/photoprism/README.md
- examples/community/photoprism/bw.data/configs/modsec-crs/allowmedia.conf
- examples/community/photoprism/docker-compose.yml
- examples/community/photoprism/photoprism-compose.yml
Example configuration to use photoprism with bunkerweb docker integration. Bunkerweb is configured with autoconf and UI
Photoprism works for all I was able to test, with mod_security enabled.
> Photoprism example config

- src/ui/app/lang_config.py
- src/ui/app/static/locales/README.md
- src/ui/app/static/locales/tw.json
I've submitted a pull request before, I've changed the file name and resubmitted it now (because I accidentally closed the last request)
> Add Traditional Chinese translation

- README.md
Update README to remove temporarily BunkerWeb Cloud
> Update README to remove temporarily BunkerWeb Cloud

- src/common/core/badbehavior/badbehavior.lua
- src/common/core/badbehavior/ui/actions.py
- src/common/core/metrics/metrics.lua
- src/ui/app/static/js/pages/plugin_page.js
- src/ui/app/templates/plugin_page.html
This commit adds more metrics to bad behavior and displays the metrics to its corresponding UI page.
> Bad behavior metrics

- src/all-in-one/Dockerfile
- src/bw/Dockerfile
- src/bw/lua/bunkerweb/helpers.lua
> Revert "bw - optimize variables loading in init phase"

- README.md
> docs: Updated supported languages

- src/common/core/letsencrypt/letsencrypt.lua
Related to issue #2695 and https://github.com/bunkerity/bunkerweb/commit/c370fce838ce6062bc5a7ecf685d0ccd0096b00c
For the MULTISITE part
> Fix Let's Encrypt wildcard cert handling with multi-value SERVER_NAME
